apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-nginx
  namespace: synapse
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - matrix.min-wave.com
    secretName: matrix-min-wave-tls
  rules:
  - host: matrix.min-wave.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: synapse-service
            port:
              number: 8008