apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-pv
  namespace: synapse
  labels:
    pvc_type: synapse-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
  path: /etc/matrix/synapse/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pv-claim
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      pvc_type:  synapse-pv