apiVersion: v1
kind: Service
metadata:
  name: synapse-service
  namespace: synapse
  labels:
    app: synapse
spec:
  ports:
  - name: http
    port: 8008
    protocol: TCP
    targetPort: 80
  selector:
    app: synapse
  type: LoadBalance
  # clusterIP: None