apiVersion: v1
kind: ConfigMap
metadata:
  name: coturn-conf
  namespace: synapse
data:
  coturn.conf: |
    server-name=turn.example.org
    #This domain needs to point to your Public IP under which coturn will be reachable through
    realm=turn.example.org
    # relay-ip=10.233.104.64
    listening-ip=5.34.193.115
    #If dont want to use TLS replace with listening-port=5349
    tls-listening-port=5349
    # listening-port=5349
    min-port=10000
    max-port=20000
    verbose
    use-auth-secret
    static-auth-secret="RUqtl1gPfOLaiGHkv3s/nQw384N+BgJYsiPK+Gbjijs="
    #If you want to disable TLS delete the next two lines
    cert=/var/run/secret/tls.crt
    pkey=/var/run/secret/tls.key
    no-cli
