apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: synapse
  labels:
    pvc_type: postgres-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/matrix/postgres/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: synapse
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  selector:
    matchLabels:
      pvc_type:  postgres-pv