apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: matrix-synapse
  labels:
    pvc_type: postgres-pv
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /etc/matrix/postgres/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: matrix-synapse
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
#  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  # selector:
  #   matchLabels:
  #     pvc_type: postgres-pv